from dominio.erros.erro_de_dominio import ErroDeDominio
